apiVersion: apps/v1
kind: Deployment
metadata:
  name: bn256-portfolio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bn256-portfolio
  template:
    metadata:
      labels:
        app: bn256-portfolio
    spec:
      containers:
      - name: bn256-portfolio
        image: bn256-portfolio
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
